[build]
builder = "nixpacks"
buildCommand = "cd podcast-api && npm install"

[deploy]
startCommand = "cd podcast-api && npm run railway:start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10
