[project]
name = "podcast-app"

[services.podcast-api]
root = "podcast-api"
start = "npm run dev"

[services.podcast-client]
root = "podcast-client"
start = "npm run dev"  # or `npm run build && npm run preview` for production
